### ISSUE TITLE
Add package to archdroid

### ISSUE THREAD

**Issue by JartX** [archdroid-org/pkgbuilds#2]
@jgmdev buenas Jefferson, me gustaría subir un paquete compilado para Arm64, pero no sé cómo podría publicarlo, tengo el PKGBUILD osease, la carpeta para makepkg.

Se trata de NeoVim.

**Comment by jgmdev** [comment]
Saludos, [neovim](https://archlinuxarm.org/packages/aarch64/neovim) esta en el repositorio oficial de archlinuxarm, tiene el paquete que indicas algo especial? En todo caso siempre que sea un PKGBUILD que compile del código fuente y repositorios oficiales no hay problema siempre y cuando la funcionalidad que ofrezca sea substancialmente diferente a la ya ofrecida por el paquete oficial.

**Comment by JartX** [comment]
> Saludos, [neovim](https://archlinuxarm.org/packages/aarch64/neovim) esta en el repositorio oficial de archlinuxarm, tiene el paquete que indicas algo especial? En todo caso siempre que sea un PKGBUILD que compile del código fuente y repositorios oficiales no hay problema siempre y cuando la funcionalidad que ofrezca sea substancialmente diferente a la ya ofrecida por el paquete oficial.

Aquí lo tienes: https://drive.google.com/file/d/1jhfqFVWHBG6PKgzl9H8rGhq8xN8B5WSW/view?usp=sharing 
Es el paquete de neovim-git adaptado a nvim 0.6, ahora mismo el de stock no compila correctamente, dado que los comandos de gestión son erróneos y el paquete neovim en arm64 oficial de archlinux, va por la versión 0.4 el cual está obsoleto y no permite el uso de plugins nuevos con lua.

**Comment by jgmdev** [comment]
Disculpa por la tardanza, agregue el paquete de neovim-git que compartiste aunque ya ArchLinuxARM actualizo el neovim a la version 0.5. Si en el futuro este paquete necesita algún cambio puedes enviar un PR.

**Comment by JartX** [comment]
Dont worry :) el nuestro es NeoVim 0.6
