### ISSUE TITLE
package `mesa-devel-git` miss provides `opencl-driver`

### ISSUE THREAD

**Issue by rhjdvsgsgks** [archdroid-org/pkgbuilds#3]
depends error will happen when install package which requiring `opencl-driver`

**Comment by jgmdev** [comment]
Added the entry to provides list, thanks for reporting.

**Comment by rhjdvsgsgks** [comment]
`clang` is also missing as a depends or optdepends, without that opencl will not works
see https://github.com/archlinux/svntogit-packages/blob/5bb7efd1c6215b61f4db6bb9529d162db3a1b355/trunk/PKGBUILD#L113 or https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mesa-git&id=d371fe35e08141d67d8673cb8597e66c5842a3e0#n76
